version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bearbite-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fycvidlmuzpp"
s3_prefix = "bearbite-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
